don't set ethernet0.* settings if we're ignoring ethernet
We were running into the following error trying to build a fresh template:

Error: OVF Package is not supported by target:
 - Line -1: Unsupported value 'ethernet0.networkName' for attribute 'key' on element 'ExtraConfig'.

Since our (internal) template also has "remove_ethernet": "true" we
don't seem to need this setting. Let's ignore it then.